### PR TITLE
Default attributes only "name", "path" and "children"

### PR DESCRIPTION
**Pull request by Momijiichigo**
I changed the code a little bit to make default attributes only "name", "path" and "children".
[issue thread](https://github.com/mihneadb/node-directory-tree/issues/74)

### CODE REVIEW

**Comment by mihneadb** [comment]
Thanks for this! Can you please merge the latest master so GIthub checks are included? It seems tests are not passing.

**Comment by Momijiichigo** [comment]
Hi! I included Github checks! Please check the test script where I changed, to produce the same result as before 
(i.e. I added `attributes: ['size','type','extension']` option in the test code.)

**Review by mihneadb — APPROVED** [review]
Thanks!

**Comment by loshchini** [comment]
The release with this fix ruined semver 😢

**Comment by mihneadb** [comment]
Sorry to hear that. You mean 2.4.0?

**Comment by loshchini** [comment]
Yeah, specifically, removing from default attributes "size", "extension" and "type" was breaking changes. Just paying attention :)

**Comment by mihneadb** [comment]
You're right, it should have turned into 3.0.0 since it is a breaking change. Sorry about that, will make a release. Thanks for notifying!

**Comment by mihneadb** [comment]
Deprecated 2.4.0, can't unpublish it now. Published 3.0.0. 
Thanks again.

**Comment by loshchini** [comment]
Thanks for reaction!

**Pull request merged**
