### PR TITLE
store extension and check is directory

### PR DESCRIPTION
**Pull request by webcarrot**
Store regular files extension.
Make sure that directory is directory.
Skip other type of files - devices, symlinks, FIFO and sockets

### CODE REVIEW

**Comment by mihnea-dobrescubalaur-hs** [comment]
Hey, thanks for the PR!
Please update the readme with the extension stuff as well.
I think as of this PR the tool will not be following symlinks, right? Maybe we can add that as an option.

**Comment by GAumala** [comment]
Skipping symlinks should be optional. I'm using this module to represent the tree of a symlink in my express's public folder

**Comment by webcarrot** [comment]
My, mistake/laziness,

fs.statSync use fs.stat() that [not recognize symlink as symlink](https://nodejs.org/api/fs.html#fs_class_fs_stats) - so "symlinks" will not be skipped ( until they point to the file/directory not FIFO, device or socket ).

PS. sorry for my English.

**Comment by mihneadb** [comment]
LGTM! Thanks!

**Pull request merged**
