### PR TITLE
add declare file for this project

### PR DESCRIPTION
**Pull request by bgdsh**

### CODE REVIEW

**Comment by bgdsh** [comment]
please help to merge this PR on your convenient.

**Comment by bgdsh** [comment]
I'm glad doing this. May I ask when will you publish the next version to npmjs.com?

**Comment by mihneadb** [comment]
Already did! :) https://www.npmjs.com/package/directory-tree/v/2.1.1

**Comment by bgdsh** [comment]
nice!!! thanks!!!

**Pull request merged**
