### PR TITLE
Accept options object

### PR DESCRIPTION
**Pull request by manatarms**
I've added the ability to accept and options object.
I updated the `tests` 
Updated `README`

I hope you don't mind that I didn't keep the if statement inline, it got pretty long :)
Let me know if you have any concerns.
Cheers.

### CODE REVIEW

**Comment by manatarms** [comment]
Woops! Forgot to bump the version. But I'm assuming you'll do that when we incorporate all of the changes. How would you like to handle the breaking change?

**Comment by mihneadb** [comment]
And yes, we'd have to bump the major version, but I'd do it after the excludes part.

**Comment by manatarms** [comment]
Yup. I didn't want to make such a major change and include the excludes. If something breaks we could trace it back to two separate PRs :)

**Comment by manatarms** [comment]
Will you merge this and then wait for me to do the excludes before publishing?

**Comment by mihneadb** [comment]
Yes! Thanks!

**Pull request merged**
